### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Pdzly** [InfinityBotList/Popplio#3]
I just wanted to give you feedback how my experience with the v4 was.

What things i noticed was good:

- Better Design in general
- Interactive usage of the Favicon of the Page
- Your Main Color comes out more than before
- It is / was good compatible with a Dark Mode Extension ( like Dark Reader )
- Good interactivity
- Some css? or js issues fixed? ( You click your avatar and it STAYS open and doesnt get closed after exiting the popup )
- Better Lazy loading
- Better Organisation of the Buttons in the Account options
- Good visibility of Privacy Statement and TOS
- Cool new Theme options for Users
- More information on like Applications etc. on the Profile

was not good:
- The borders in the main page is a little bit too much
- The Advanced Search doesnt extend the background color
(https://i.imgur.com/XjLXzWE.png)
- Nothing else

Thanks for reading it! For questions just comment ;) if it isnt appretiated or wrong posted just close it.

Have a great day!
Rooki / Pdzly

**Comment by cheesycod** [comment]
Fixed these issues, reopen if you have more
